import os
import shutil
import uuid
from collections import defaultdict
from importlib.metadata import PackageNotFoundError, version

from fastapi import UploadFile
from langchain_community.document_loaders import PyPDFLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter

UPLOAD_DIR = "uploads/papers"
INGESTION_VERSION = "page-offset-v1"


class DocumentProcessor:
    def __init__(self):
        os.makedirs(UPLOAD_DIR, exist_ok=True)
        self.text_splitter = RecursiveCharacterTextSplitter(
            chunk_size=1000,
            chunk_overlap=200,
            length_function=len,
            add_start_index=True,
        )

    @staticmethod
    def parser_metadata() -> dict[str, str]:
        """Return stable parser metadata used for provenance records."""
        try:
            parser_version = version("langchain-community")
        except PackageNotFoundError:
            parser_version = "unknown"
        return {
            "parser_name": "PyPDFLoader",
            "parser_version": parser_version,
            "ingestion_version": INGESTION_VERSION,
        }

    async def save_upload_file(self, upload_file: UploadFile) -> str:
        """Lưu file từ request xuống thư mục vật lý."""
        file_id = str(uuid.uuid4())
        safe_filename = f"{file_id}_{upload_file.filename}"
        file_path = os.path.join(UPLOAD_DIR, safe_filename)

        with open(file_path, "wb") as buffer:
            shutil.copyfileobj(upload_file.file, buffer)

        return file_path

    def _attach_chunk_metadata(self, pages, chunks) -> None:
        """Attach page-relative offsets and deterministic per-page chunk indexes.

        `start_index` is generated by LangChain's TextSplitter and is relative
        to the exact `page.page_content` supplied to the splitter.  We keep that
        coordinate system unchanged so later grounding can map evidence back to
        the raw extracted page text stored in PageText.
        """
        page_text_by_number = {
            int(page.metadata.get("page", index)): page.page_content
            for index, page in enumerate(pages)
        }
        chunk_counter: defaultdict[int, int] = defaultdict(int)

        for chunk in chunks:
            page_number = int(chunk.metadata.get("page", 0))
            if page_number not in page_text_by_number:
                raise ValueError(f"Chunk references unknown page {page_number}.")

            raw_start = chunk.metadata.get("start_index")
            if raw_start is None:
                raise ValueError(
                    "Chunk is missing start_index. Ensure add_start_index=True on the text splitter."
                )

            start = int(raw_start)
            end = start + len(chunk.page_content)
            page_text = page_text_by_number[page_number]

            if start < 0 or end > len(page_text) or page_text[start:end] != chunk.page_content:
                raise ValueError(
                    "Invalid chunk offset: page_text[page_char_start:page_char_end] "
                    "does not reconstruct chunk.page_content exactly."
                )

            chunk.metadata["chunk_index"] = chunk_counter[page_number]
            chunk.metadata["page_char_start"] = start
            chunk.metadata["page_char_end"] = end
            # Preserve LangChain's start_index for backwards/debug compatibility.
            chunk_counter[page_number] += 1

    def extract_and_chunk(self, file_path: str):
        """Đọc PDF theo trang và cắt chunk với provenance offset theo từng trang."""
        if not os.path.exists(file_path):
            raise FileNotFoundError(f"File not found: {file_path}")

        loader = PyPDFLoader(file_path)
        pages = loader.load()
        chunks = self.text_splitter.split_documents(pages)
        self._attach_chunk_metadata(pages, chunks)

        return pages, chunks
