import os
import shutil
import uuid
from collections import defaultdict
from importlib.metadata import PackageNotFoundError, version

from fastapi import UploadFile

from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_core.documents import Document

UPLOAD_DIR = "uploads/papers"
INGESTION_VERSION = "page-offset-v1"


class DocumentProcessor:
    def __init__(self):
        os.makedirs(UPLOAD_DIR, exist_ok=True)
        self.text_splitter = RecursiveCharacterTextSplitter(
            chunk_size=2000,
            chunk_overlap=400,
            length_function=len,
            add_start_index=True,
        )

    @staticmethod
    def parser_metadata() -> dict[str, str]:
        """Return stable parser metadata used for provenance records."""
        try:
            parser_version = version("pypdf")
            parser_name = "pypdf"
        except PackageNotFoundError:
            try:
                parser_version = version("pymupdf")
                parser_name = "PyMuPDF"
            except PackageNotFoundError:
                parser_version = "unknown"
                parser_name = "pdf_parser"
        return {
            "parser_name": parser_name,
            "parser_version": parser_version,
            "ingestion_version": INGESTION_VERSION,
        }

    async def save_upload_file(self, upload_file: UploadFile, project_id: str | None = None) -> str:
        """Lưu file từ request xuống thư mục vật lý, scoped theo project_id.

        Nếu project_id được cung cấp, file được lưu vào uploads/papers/{project_id}/
        để đảm bảo không bị lẫn giữa các project và dễ cleanup sau này.
        """
        file_id = str(uuid.uuid4())
        safe_filename = f"{file_id}_{upload_file.filename}"

        if project_id:
            project_dir = os.path.join(UPLOAD_DIR, project_id)
            os.makedirs(project_dir, exist_ok=True)
            file_path = os.path.join(project_dir, safe_filename)
        else:
            file_path = os.path.join(UPLOAD_DIR, safe_filename)

        content = await upload_file.read()
        with open(file_path, "wb") as f:
            f.write(content)

        return file_path

    def _attach_chunk_metadata(self, pages, chunks) -> None:
        """Attach page-relative offsets and deterministic per-page chunk indexes.

        `start_index` is generated by LangChain's TextSplitter and is relative
        to the exact `page.page_content` supplied to the splitter.  We keep that
        coordinate system unchanged so later grounding can map evidence back to
        the raw extracted page text stored in PageText.
        """
        page_text_by_number = {
            int(page.metadata.get("page", index)): page.page_content
            for index, page in enumerate(pages)
        }
        chunk_counter: defaultdict[int, int] = defaultdict(int)

        for chunk in chunks:
            page_number = int(chunk.metadata.get("page", 0))
            if page_number not in page_text_by_number:
                raise ValueError(f"Chunk references unknown page {page_number}.")

            raw_start = chunk.metadata.get("start_index")
            if raw_start is None:
                raise ValueError(
                    "Chunk is missing start_index. Ensure add_start_index=True on the text splitter."
                )

            start = int(raw_start)
            end = start + len(chunk.page_content)
            page_text = page_text_by_number[page_number]

            if start < 0 or end > len(page_text) or page_text[start:end] != chunk.page_content:
                # Try finding exact snippet in page_text
                found_start = page_text.find(chunk.page_content)
                if found_start != -1:
                    start = found_start
                    end = start + len(chunk.page_content)
                else:
                    # Clamp start and end safely
                    start = max(0, min(start, len(page_text)))
                    end = max(start, min(end, len(page_text)))

            chunk.metadata["chunk_index"] = chunk_counter[page_number]
            chunk.metadata["page_char_start"] = start
            chunk.metadata["page_char_end"] = end
            # Preserve LangChain's start_index for backwards/debug compatibility.
            chunk_counter[page_number] += 1

    def extract_and_chunk(self, file_path: str, paper_title: str | None = None):
        """Đọc PDF theo trang và cắt chunk với provenance offset theo từng trang."""
        if not os.path.exists(file_path):
            raise FileNotFoundError(f"File not found: {file_path}")

        pages = []
        try:
            import fitz
            doc = fitz.open(file_path)
            for i, page in enumerate(doc):
                pages.append(
                    Document(
                        page_content=page.get_text(),
                        metadata={"source": file_path, "page": i}
                    )
                )
            doc.close()
        except ImportError:
            import pypdf
            reader = pypdf.PdfReader(file_path)
            for i, page in enumerate(reader.pages):
                pages.append(
                    Document(
                        page_content=page.extract_text() or "",
                        metadata={"source": file_path, "page": i}
                    )
                )
        chunks = self.text_splitter.split_documents(pages)
        self._attach_chunk_metadata(pages, chunks)

        if paper_title:
            for chunk in chunks:
                chunk.metadata["paper_title"] = paper_title

        return pages, chunks
