"""Persistence helpers for PDF ingestion provenance."""
from __future__ import annotations

import hashlib
import uuid

from sqlalchemy.ext.asyncio import AsyncSession

from src.models.db_models import PDFChunk, PDFStatus, PageText, Paper


def _sha256_text(value: str) -> str:
    return hashlib.sha256(value.encode("utf-8")).hexdigest()


async def persist_pdf_provenance(
    *,
    db: AsyncSession,
    paper: Paper,
    pages,
    chunks,
    parser_metadata: dict[str, str],
) -> uuid.UUID:
    """Persist one immutable ingestion version and enrich Chroma metadata.

    The raw page text is stored exactly as returned by PyPDFLoader.  Chunk
    offsets therefore stay in the same page-relative coordinate system.
    Existing PageText/PDFChunk versions are intentionally retained so evidence
    created by an older synthesis run remains auditable.
    """
    ingestion_id = uuid.uuid4()
    page_rows_by_number: dict[int, PageText] = {}
    page_rows: list[PageText] = []

    for fallback_index, page in enumerate(pages):
        page_number = int(page.metadata.get("page", fallback_index))
        raw_text = page.page_content
        page_row = PageText(
            id=uuid.uuid4(),
            paper_id=paper.id,
            ingestion_id=ingestion_id,
            page_number=page_number,
            full_text=raw_text,
            content_hash=_sha256_text(raw_text),
            parser_name=parser_metadata["parser_name"],
            parser_version=parser_metadata["parser_version"],
            ingestion_version=parser_metadata["ingestion_version"],
        )
        page_rows_by_number[page_number] = page_row
        page_rows.append(page_row)

    chunk_rows: list[PDFChunk] = []
    for chunk in chunks:
        page_number = int(chunk.metadata.get("page", 0))
        page_row = page_rows_by_number.get(page_number)
        if page_row is None:
            raise ValueError(f"Chunk references missing PageText page {page_number}.")

        start = int(chunk.metadata["page_char_start"])
        end = int(chunk.metadata["page_char_end"])
        chunk_index = int(chunk.metadata["chunk_index"])

        if page_row.full_text[start:end] != chunk.page_content:
            raise ValueError(
                "Cannot persist chunk provenance: raw PageText does not reconstruct chunk content."
            )

        chunk_row = PDFChunk(
            id=uuid.uuid4(),
            paper_id=paper.id,
            page_text_id=page_row.id,
            ingestion_id=ingestion_id,
            chunk_text=chunk.page_content,
            page=page_number,
            chunk_index=chunk_index,
            page_char_start=start,
            page_char_end=end,
            # Keep legacy fields populated for old readers during transition.
            char_start=start,
            char_end=end,
        )
        chunk_rows.append(chunk_row)

        # Canonical identifiers are generated by our DB layer, not by the LLM.
        chunk.metadata["paper_id"] = str(paper.id)
        chunk.metadata["page_text_id"] = str(page_row.id)
        chunk.metadata["chunk_id"] = str(chunk_row.id)
        chunk.metadata["ingestion_id"] = str(ingestion_id)
        chunk.metadata["page"] = page_number
        chunk.metadata["chunk_index"] = chunk_index
        chunk.metadata["page_char_start"] = start
        chunk.metadata["page_char_end"] = end

    db.add_all(page_rows)
    db.add_all(chunk_rows)
    paper.active_ingestion_id = ingestion_id
    paper.pdf_status = PDFStatus.user_uploaded
    await db.flush()
    return ingestion_id
