"""Persistence helpers for PDF ingestion provenance."""
from __future__ import annotations

import hashlib
import uuid

from sqlalchemy.ext.asyncio import AsyncSession

from src.models.db_models import PDFChunk, PDFStatus, PageText, Paper


def _sha256_text(value: str) -> str:
    return hashlib.sha256(value.encode("utf-8")).hexdigest()


def _sanitize_text(value: str) -> str:
    """Replace null bytes that PostgreSQL UTF-8 encoding rejects (0x00).
    Replacing with a space preserves string length and chunk offsets.
    """
    return value.replace("\x00", " ")


async def persist_pdf_provenance(
    *,
    db: AsyncSession,
    paper: Paper,
    pages,
    chunks,
    parser_metadata: dict[str, str],
) -> uuid.UUID:
    """Persist one immutable ingestion version and enrich Chroma metadata.

    The raw page text is stored exactly as returned by PyPDFLoader.  Chunk
    offsets therefore stay in the same page-relative coordinate system.
    Existing PageText/PDFChunk versions are intentionally retained so evidence
    created by an older synthesis run remains auditable.
    """
    ingestion_id = uuid.uuid4()
    page_rows_by_number: dict[int, PageText] = {}
    page_rows: list[PageText] = []

    for fallback_index, page in enumerate(pages):
        page_number = int(page.metadata.get("page", fallback_index))
        raw_text = _sanitize_text(page.page_content)
        page_row = PageText(
            id=uuid.uuid4(),
            paper_id=paper.id,
            ingestion_id=ingestion_id,
            page_number=page_number,
            full_text=raw_text,
            content_hash=_sha256_text(raw_text),
            parser_name=parser_metadata["parser_name"],
            parser_version=parser_metadata["parser_version"],
            ingestion_version=parser_metadata["ingestion_version"],
        )
        page_rows_by_number[page_number] = page_row
        page_rows.append(page_row)

    chunk_rows: list[PDFChunk] = []
    for chunk in chunks:
        page_number = int(chunk.metadata.get("page", 0))
        page_row = page_rows_by_number.get(page_number)
        if page_row is None:
            raise ValueError(f"Chunk references missing PageText page {page_number}.")

        start = int(chunk.metadata["page_char_start"])
        end = int(chunk.metadata["page_char_end"])
        chunk_index = int(chunk.metadata["chunk_index"])

        chunk.page_content = _sanitize_text(chunk.page_content)
        if page_row.full_text[start:end] != chunk.page_content:
            raise ValueError(
                "Cannot persist chunk provenance: raw PageText does not reconstruct chunk content."
            )

        chunk_row = PDFChunk(
            id=uuid.uuid4(),
            paper_id=paper.id,
            page_text_id=page_row.id,
            ingestion_id=ingestion_id,
            chunk_text=chunk.page_content,
            page=page_number,
            chunk_index=chunk_index,
            page_char_start=start,
            page_char_end=end,
            # Keep legacy fields populated for old readers during transition.
            char_start=start,
            char_end=end,
        )
        chunk_rows.append(chunk_row)

        # Canonical identifiers are generated by our DB layer, not by the LLM.
        chunk.metadata["paper_id"] = str(paper.id)
        chunk.metadata["page_text_id"] = str(page_row.id)
        chunk.metadata["chunk_id"] = str(chunk_row.id)
        chunk.metadata["ingestion_id"] = str(ingestion_id)
        chunk.metadata["page"] = page_number
        chunk.metadata["chunk_index"] = chunk_index
        chunk.metadata["page_char_start"] = start
        chunk.metadata["page_char_end"] = end
        chunk.metadata["source"] = str(paper.file_path) if paper.file_path else f"paper_{paper.id}.pdf"
        chunk.metadata["paper_title"] = str(paper.title) if paper.title else "Unknown Title"

    db.add_all(page_rows)
    db.add_all(chunk_rows)
    paper.active_ingestion_id = ingestion_id
    paper.pdf_status = PDFStatus.user_uploaded
    await db.flush()
    return ingestion_id


async def ensure_paper_ingested(db: AsyncSession, paper: Paper) -> uuid.UUID:
    """Ensure a Paper has an active_ingestion_id.
    If active_ingestion_id is already set, return it.
    If paper.file_path exists and is readable, run PDF extractor and persist provenance.
    Otherwise (e.g. metadata/search paper), construct a synthetic provenance page from
    title + abstract text and persist provenance.
    """
    if paper.active_ingestion_id is not None:
        return paper.active_ingestion_id

    import os
    from src.services.document_processor import DocumentProcessor
    from src.services.vector_store import vector_store_service
    from langchain_core.documents import Document

    processor = DocumentProcessor()

    if paper.file_path and os.path.exists(paper.file_path):
        try:
            pages, chunks = processor.extract_and_chunk(paper.file_path)
            if chunks and any(c.page_content.strip() for c in chunks):
                ingestion_id = await persist_pdf_provenance(
                    db=db,
                    paper=paper,
                    pages=pages,
                    chunks=chunks,
                    parser_metadata=processor.parser_metadata()
                )
                await vector_store_service.stage_documents_for_paper(str(paper.id), chunks)
                await db.commit()
                return ingestion_id
        except Exception as e:
            print(f"Warning: Failed PDF re-ingestion for '{paper.title}': {e}")

    # Fallback for metadata / search paper (or unparseable PDF)
    abstract_text = (paper.abstract or "").strip()
    if len(abstract_text) < 10:
        abstract_text = f"Title: {paper.title}. No detailed abstract provided."

    authors_str = paper.authors if isinstance(paper.authors, str) else ", ".join(paper.authors or [])
    full_page_content = f"Title: {paper.title}\nAuthors: {authors_str}\nJournal: {paper.journal or 'N/A'} ({paper.year or 'N/A'})\nAbstract: {abstract_text}"
    
    page = Document(page_content=full_page_content, metadata={"page": 0})
    chunk = Document(
        page_content=full_page_content,
        metadata={
            "page": 0,
            "chunk_index": 0,
            "page_char_start": 0,
            "page_char_end": len(full_page_content)
        }
    )
    
    ingestion_id = await persist_pdf_provenance(
        db=db,
        paper=paper,
        pages=[page],
        chunks=[chunk],
        parser_metadata={
            "parser_name": "metadata_fallback",
            "parser_version": "1.0",
            "ingestion_version": "1.0"
        }
    )
    try:
        await vector_store_service.stage_documents_for_paper(str(paper.id), [chunk])
    except Exception:
        pass
    await db.commit()
    return ingestion_id

