"""Persistence helpers for PDF ingestion provenance."""
from __future__ import annotations

import hashlib
import uuid

from sqlalchemy.ext.asyncio import AsyncSession

from src.models.db_models import PageText, Paper, PDFChunk, PDFStatus


def _sha256_text(value: str) -> str:
    return hashlib.sha256(value.encode("utf-8")).hexdigest()


def _sanitize_text(value: str) -> str:
    """Replace null bytes that PostgreSQL UTF-8 encoding rejects (0x00).
    Replacing with a space preserves string length and chunk offsets.
    """
    return value.replace("\x00", " ")


async def persist_pdf_provenance(
    *,
    db: AsyncSession,
    paper: Paper,
    pages,
    chunks,
    parser_metadata: dict[str, str],
) -> uuid.UUID:
    """Persist one immutable ingestion version and enrich Chroma metadata.

    The raw page text is stored exactly as returned by PyPDFLoader.  Chunk
    offsets therefore stay in the same page-relative coordinate system.
    Existing PageText/PDFChunk versions are intentionally retained so evidence
    created by an older synthesis run remains auditable.
    """
    ingestion_id = uuid.uuid4()
    page_rows_by_number: dict[int, PageText] = {}
    page_rows: list[PageText] = []

    for fallback_index, page in enumerate(pages):
        page_number = int(page.metadata.get("page", fallback_index))
        raw_text = _sanitize_text(page.page_content)
        page_row = PageText(
            id=uuid.uuid4(),
            paper_id=paper.id,
            ingestion_id=ingestion_id,
            page_number=page_number,
            full_text=raw_text,
            content_hash=_sha256_text(raw_text),
            parser_name=parser_metadata["parser_name"],
            parser_version=parser_metadata["parser_version"],
            ingestion_version=parser_metadata["ingestion_version"],
        )
        page_rows_by_number[page_number] = page_row
        page_rows.append(page_row)

    chunk_rows: list[PDFChunk] = []
    for chunk in chunks:
        page_number = int(chunk.metadata.get("page", 0))
        page_row = page_rows_by_number.get(page_number)
        if page_row is None:
            raise ValueError(f"Chunk references missing PageText page {page_number}.")

        start = int(chunk.metadata["page_char_start"])
        end = int(chunk.metadata["page_char_end"])
        chunk_index = int(chunk.metadata["chunk_index"])

        chunk.page_content = _sanitize_text(chunk.page_content)
        if page_row.full_text[start:end] != chunk.page_content:
            raise ValueError(
                "Cannot persist chunk provenance: raw PageText does not reconstruct chunk content."
            )

        chunk_row = PDFChunk(
            id=uuid.uuid4(),
            paper_id=paper.id,
            page_text_id=page_row.id,
            ingestion_id=ingestion_id,
            chunk_text=chunk.page_content,
            page=page_number,
            chunk_index=chunk_index,
            page_char_start=start,
            page_char_end=end,
            # Keep legacy fields populated for old readers during transition.
            char_start=start,
            char_end=end,
        )
        chunk_rows.append(chunk_row)

        # Canonical identifiers are generated by our DB layer, not by the LLM.
        chunk.metadata["paper_id"] = str(paper.id)
        chunk.metadata["page_text_id"] = str(page_row.id)
        chunk.metadata["chunk_id"] = str(chunk_row.id)
        chunk.metadata["ingestion_id"] = str(ingestion_id)
        chunk.metadata["page"] = page_number
        chunk.metadata["chunk_index"] = chunk_index
        chunk.metadata["page_char_start"] = start
        chunk.metadata["page_char_end"] = end
        chunk.metadata["source"] = str(paper.file_path) if paper.file_path else f"paper_{paper.id}.pdf"
        chunk.metadata["paper_title"] = str(paper.title) if paper.title else "Unknown Title"

    db.add_all(page_rows)
    db.add_all(chunk_rows)
    paper.active_ingestion_id = ingestion_id
    paper.pdf_status = PDFStatus.user_uploaded
    await db.flush()
    return ingestion_id


class PdfIngestionError(RuntimeError):
    """A document that should have been read in full could not be parsed."""


async def _index_chunks(
    db: AsyncSession, *, paper: Paper, chunks, ingestion_id: uuid.UUID
) -> None:
    """Write chunks to the vector store, recording the outcome either way.

    The order matters. The status is committed as INDEXING *before* the write,
    so a process killed midway leaves the paper visibly stuck rather than
    looking complete; it becomes READY only once the vectors are actually in.

    Previously the DB was committed first and the vector write swallowed its own
    errors, so an embedding call that hit a quota limit produced a paper marked
    fully ingested with nothing behind it in Chroma -- and retrieval had no way
    to tell it apart from a real one.
    """
    from src.services import index_registry
    from src.services.vector_store import vector_store_service

    index = await index_registry.get_or_create_index(db, vector_store_service.identity)
    await index_registry.mark_indexing(
        db, paper_id=paper.id, index=index, ingestion_id=ingestion_id
    )
    await db.commit()

    try:
        old_ids = await vector_store_service.stage_documents_for_paper(str(paper.id), chunks)
    except Exception as exc:
        await index_registry.mark_failed(db, paper_id=paper.id, index=index, error=str(exc))
        await db.commit()
        raise

    await index_registry.mark_ready(
        db, paper_id=paper.id, index=index, chunk_count=len(chunks)
    )
    await db.commit()

    if old_ids:
        await vector_store_service.delete_document_ids(old_ids)


async def ensure_paper_ingested(db: AsyncSession, paper: Paper) -> uuid.UUID:
    """Ensure a Paper has an active_ingestion_id and is present in the index.

    If ``paper.file_path`` points at a readable PDF, that PDF is the evidence.
    Otherwise the paper is metadata-only (a search result with no full text)
    and its title/abstract stand in, recorded as such.
    """
    if paper.active_ingestion_id is not None:
        # Nothing to do. This branch used to re-read every chunk from Postgres
        # and push them all back into Chroma on each call. Chroma minted a new
        # id per document, so an already-ingested paper gained one full copy of
        # itself per synthesis run: storage grew linearly and top-k retrieval
        # filled with duplicates of the same passage, quietly crowding out other
        # evidence. Restoring genuinely missing vectors is
        # VectorStoreService.recover_vectors_for_paper's job, and it now runs
        # against the identity the vectors were built with.
        return paper.active_ingestion_id

    import os

    from langchain_core.documents import Document

    from src.services.document_processor import DocumentProcessor

    processor = DocumentProcessor()

    if paper.file_path and os.path.exists(paper.file_path):
        try:
            pages, chunks = processor.extract_and_chunk(paper.file_path)
        except Exception as exc:
            # Deliberately not falling through to the title/abstract path below.
            # A 30-page PDF that fails to parse used to be silently replaced by
            # a single chunk holding its title and abstract, recorded as a
            # successful ingestion -- so synthesis went on to cite the paper as
            # though it had been read in full. For a literature review tool that
            # is a claim about evidence that is not true.
            raise PdfIngestionError(
                f"Could not extract text from the PDF for {paper.title!r} "
                f"({paper.file_path}): {exc}. The document has not been "
                "ingested; re-upload it or remove the file to ingest this "
                "paper from its abstract instead."
            ) from exc

        if not chunks or not any(c.page_content.strip() for c in chunks):
            raise PdfIngestionError(
                f"The PDF for {paper.title!r} parsed but yielded no text. It is "
                "most likely a scan and needs OCR before it can be used as "
                "evidence."
            )

        ingestion_id = await persist_pdf_provenance(
            db=db,
            paper=paper,
            pages=pages,
            chunks=chunks,
            parser_metadata=processor.parser_metadata()
        )
        await db.flush()
        await _index_chunks(db, paper=paper, chunks=chunks, ingestion_id=ingestion_id)
        return ingestion_id

    # Metadata-only paper: there is no full text to read, so the abstract is
    # genuinely all the evidence there is. parser_name records that, so
    # downstream consumers can tell this apart from a parsed document.
    abstract_text = (paper.abstract or "").strip()
    if len(abstract_text) < 10:
        raise PdfIngestionError(
            f"{paper.title!r} has neither a readable PDF nor an abstract, so "
            "there is nothing to index. Upload the full text first."
        )

    authors_str = paper.authors if isinstance(paper.authors, str) else ", ".join(paper.authors or [])
    full_page_content = f"Title: {paper.title}\nAuthors: {authors_str}\nJournal: {paper.journal or 'N/A'} ({paper.year or 'N/A'})\nAbstract: {abstract_text}"

    page = Document(page_content=full_page_content, metadata={"page": 0})
    chunk = Document(
        page_content=full_page_content,
        metadata={
            "page": 0,
            "chunk_index": 0,
            "page_char_start": 0,
            "page_char_end": len(full_page_content)
        }
    )

    ingestion_id = await persist_pdf_provenance(
        db=db,
        paper=paper,
        pages=[page],
        chunks=[chunk],
        parser_metadata={
            "parser_name": "metadata_only",
            "parser_version": "1.0",
            "ingestion_version": "1.0"
        }
    )
    await db.flush()
    await _index_chunks(db, paper=paper, chunks=[chunk], ingestion_id=ingestion_id)
    return ingestion_id

