"""Initial schema

Revision ID: 7bbe5d089b1c
Revises: 
Create Date: 2026-08-07 15:11:48.040228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7bbe5d089b1c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('research_question', sa.Text(), nullable=False),
    sa.Column('research_field', sa.String(), nullable=False),
    sa.Column('year_from', sa.Integer(), nullable=True),
    sa.Column('year_to', sa.Integer(), nullable=True),
    sa.Column('criteria_include', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('criteria_exclude', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scopus_sources',
    sa.Column('issn', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('quartile', sa.String(), nullable=True),
    sa.Column('coverage_year_start', sa.Integer(), nullable=True),
    sa.Column('coverage_year_end', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('issn')
    )
    op.create_table('search_queries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('query_string', sa.Text(), nullable=False),
    sa.Column('strategy_label', sa.String(), nullable=True),
    sa.Column('result_count', sa.Integer(), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_duplicated_from', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['is_duplicated_from'], ['search_queries.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('synthesis_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('paper_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('status', sa.Enum('processing', 'done', 'failed', name='synthesisstatus'), nullable=True),
    sa.Column('review_markdown', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('papers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('search_query_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('authors', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('doi', sa.String(), nullable=True),
    sa.Column('issn', sa.String(), nullable=True),
    sa.Column('journal', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('dedup_key', sa.String(), nullable=False),
    sa.Column('relevance_bucket', sa.Enum('high', 'medium', 'low', 'insufficient_info', name='relevancebucket'), nullable=True),
    sa.Column('relevance_reason', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('priority_score', sa.Float(), nullable=True),
    sa.Column('screening_decision', sa.Enum('keep', 'remove', 'maybe', 'pending', name='screeningdecision'), nullable=True),
    sa.Column('scopus_status', sa.Enum('indexed', 'not_indexed', 'undetermined', name='scopusstatus'), nullable=True),
    sa.Column('scopus_quartile', sa.String(), nullable=True),
    sa.Column('coverage_year_status', sa.Enum('ok', 'out_of_coverage', 'not_applicable', name='coverageyearstatus'), nullable=True),
    sa.Column('oa_status', sa.Enum('gold', 'hybrid', 'bronze', 'green', 'closed', 'undetermined', name='oastatus'), nullable=True),
    sa.Column('pdf_status', sa.Enum('not_uploaded', 'oa_auto_fetched', 'user_uploaded', name='pdfstatus'), nullable=True),
    sa.Column('extraction_status', sa.Enum('not_extracted', 'extracted', name='extractionstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['search_query_id'], ['search_queries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedup_key')
    )
    op.create_table('citations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('synthesis_session_id', sa.UUID(), nullable=True),
    sa.Column('paper_id', sa.UUID(), nullable=True),
    sa.Column('citation_marker', sa.String(), nullable=False),
    sa.Column('review_char_start', sa.Integer(), nullable=True),
    sa.Column('review_char_end', sa.Integer(), nullable=True),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('source_char_start', sa.Integer(), nullable=True),
    sa.Column('source_char_end', sa.Integer(), nullable=True),
    sa.Column('quoted_snippet', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.ForeignKeyConstraint(['synthesis_session_id'], ['synthesis_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('extractions',
    sa.Column('paper_id', sa.UUID(), nullable=False),
    sa.Column('objective', sa.Text(), nullable=True),
    sa.Column('method', sa.Text(), nullable=True),
    sa.Column('finding', sa.Text(), nullable=True),
    sa.Column('limitation', sa.Text(), nullable=True),
    sa.Column('research_gap', sa.Text(), nullable=True),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.PrimaryKeyConstraint('paper_id')
    )
    op.create_table('pdf_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('paper_id', sa.UUID(), nullable=True),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('char_start', sa.Integer(), nullable=True),
    sa.Column('char_end', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('screening_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('paper_id', sa.UUID(), nullable=True),
    sa.Column('decision', sa.Enum('keep', 'remove', 'maybe', 'pending', name='screeningdecision'), nullable=False),
    sa.Column('ai_reason', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('user_note', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('screening_history')
    op.drop_table('pdf_chunks')
    op.drop_table('extractions')
    op.drop_table('citations')
    op.drop_table('papers')
    op.drop_table('synthesis_sessions')
    op.drop_table('search_queries')
    op.drop_table('scopus_sources')
    op.drop_table('projects')
    # ### end Alembic commands ###
