"""Criteria Generator Agent — Tự động sinh tiêu chí Inclusion/Exclusion chuẩn học thuật.

Đọc câu hỏi nghiên cứu và lĩnh vực, tự động đề xuất 3 tiêu chí chọn (Inclusion)
và 3 tiêu chí loại (Exclusion) chuẩn quốc tế.
"""

from __future__ import annotations

import logging

from pydantic import BaseModel, Field

from src.services.llm import ainvoke_with_failover

logger = logging.getLogger(__name__)

class CriteriaGenerationResult(BaseModel):
    criteria_include: list[str] = Field(default_factory=list, description="Danh sách tiêu chí chọn vào (Inclusion)")
    criteria_exclude: list[str] = Field(default_factory=list, description="Danh sách tiêu chí loại trừ (Exclusion)")

CRITERIA_PROMPT = """Bạn là Chuyên gia Tổng quan Hệ thống (Systematic Literature Review Expert).
Dựa trên đề tài nghiên cứu sau:

- Đề tài / Câu hỏi nghiên cứu: "{idea}"
- Lĩnh vực: "{research_field}"

Hãy tự động đề xuất:
1. "criteria_include" (Đúng 3-4 tiêu chí chọn vào quan trọng nhất):
   - Thời gian xuất bản (ví dụ: Các công trình từ 2021 đến nay)
   - Phương pháp & Nội dung (ví dụ: Có thử nghiệm thực nghiệm / triển khai trên mô hình thực tế hoặc môi trường giả lập chuẩn)
   - Dạng bài & Ngôn ngữ (ví dụ: Bài báo có bình duyệt - Peer-reviewed, viết bằng tiếng Anh)
2. "criteria_exclude" (Đúng 3-4 tiêu chí loại trừ chặt chẽ nhất):
   - Dạng tài liệu kém tin cậy (ví dụ: Sách tóm tắt, bài quan điểm cá nhân, bài báo chưa qua bình duyệt)
   - Phạm vi nghiên cứu không liên quan (ví dụ: Nghiên cứu lý thuyết thuần túy không có dữ liệu đối sánh hiệu năng)
   - Dữ liệu bị trùng lặp hoặc thiếu thông tin thực nghiệm

TRẢ VỀ DUY NHẤT MỘT JSON HỢP LỆ (KHÔNG THÊM MARKDOWN):
{{
  "criteria_include": [
    "Bài báo được xuất bản từ năm 2021 đến nay (đảm bảo tính cập nhật của công nghệ)",
    "Nghiên cứu có thử nghiệm thực nghiệm trên Robot thật hoặc môi trường mô phỏng chuẩn (Gazebo, Isaac Sim, MuJoCo)",
    "Bài báo được bình duyệt (Peer-reviewed) xuất bản tại các tạp chí, hội nghị uy tín bằng tiếng Anh"
  ],
  "criteria_exclude": [
    "Các bài báo ngắn (Short papers < 3 trang), bài tóm tắt hội thảo, bài viết ý kiến (Editorial/Opinion)",
    "Các nghiên cứu lý thuyết trừu tượng không cung cấp mã nguồn, tập dữ liệu hoặc kết quả đo lường cụ thể",
    "Các tài liệu không được viết bằng tiếng Anh hoặc bản sao trùng lặp nội dung"
  ]
}}
"""

async def run_criteria_generator(idea: str, research_field: str = "") -> CriteriaGenerationResult:
    """Chạy Agent Tự động Sinh Tiêu chí với Key chuyên dụng."""
    if not idea or len(idea.strip()) < 3:
        return CriteriaGenerationResult(
            criteria_include=["Bài báo xuất bản từ 2021 đến nay", "Có thử nghiệm thực nghiệm", "Viết bằng tiếng Anh"],
            criteria_exclude=["Bài tóm tắt hội thảo ngắn", "Không có số liệu đối chứng", "Tài liệu trùng lặp"]
        )

    from src.services.lora_client import call_lora_model

    # 1. THỬ GỌI LORA MODEL TRƯỚC (NẾU CÓ)
    lora_instruction = "Generate rigorous PRISMA inclusion and exclusion criteria."
    lora_input = f"Domain: {research_field}\nTopic: {idea}"
    lora_result = await call_lora_model("lora_agent2_criteria", lora_instruction, lora_input)
    if lora_result:
        return CriteriaGenerationResult(
            criteria_include=lora_result.get("include", lora_result.get("criteria_include", [])),
            criteria_exclude=lora_result.get("exclude", lora_result.get("criteria_exclude", []))
        )

    # 2. Gọi LLM qua router chung.
    #
    # Trước đây khối này tự dựng tới 5 client (3 model Gemini + Groq + OpenAI),
    # đọc key Gemini theo vị trí trong danh sách (`keys[1]`) và thử lần lượt.
    # Bảy chỗ khác trong repo có bản sao gần giống nhưng khác thứ tự, nên cùng
    # một `.env` cho ra hành vi khác nhau tuỳ tính năng đang chạy.
    prompt = CRITERIA_PROMPT.format(idea=idea.strip(), research_field=research_field.strip() or "Khoa học máy tính / AI")

    try:
        result, outcome = await ainvoke_with_failover(
            "generate_criteria",
            lambda client: client.with_structured_output(CriteriaGenerationResult),
            [("human", prompt)],
            temperature=0.3,
        )
        logger.info(
            "Criteria generated by %s (key %s) in %d attempt(s).",
            outcome.selection.profile.key, outcome.selection.credential.alias, outcome.attempts,
        )
        return result
    except Exception as exc:
        logger.warning("LLM call failed in run_criteria_generator, using academic heuristic fallback: %s", exc)
        return CriteriaGenerationResult(
            criteria_include=[
                f"Các bài báo nghiên cứu gốc tập trung vào {idea}",
                "Bài báo xuất bản trên các tạp chí Scopus/ISI hoặc hội thảo quốc tế uy tín từ năm 2020 đến nay",
                "Có kết quả thực nghiệm định lượng rõ ràng với các chỉ số đo lường chuẩn (Accuracy, F1-score, Latency)",
                "Bài báo viết bằng tiếng Anh có toàn văn (Full-text) truy cập được"
            ],
            criteria_exclude=[
                "Các bài tổng quan chung hoặc tài liệu chưa qua phản biện (Non-peer-reviewed preprints)",
                "Bài báo thiếu số liệu đối chứng hoặc không công bố rõ phương pháp thực nghiệm",
                "Các báo cáo kỹ thuật ngắn, bài xã luận hoặc tài liệu hội thảo tóm tắt dưới 4 trang",
                "Tài liệu trùng lặp hoặc không thuộc phạm vi xử lý tín hiệu/mô hình học máy"
            ]
        )
